;Jai Pal Singh
;2015kucp1038
;Write a program in LISP to perform find and replace activity, where you take a paragraph as input and find any word(input take by user) in the paragraph if it is present then replace it by any other word.

(write-line "Enter the paragraph (press Enter when paragraph complete) : ")
(setq para (read-line))
;(write-line para)
(terpri)
(write-line "Enter the word to find : ")
(setq findWord (read-line))
;(write-line findWord)
(terpri)
(write-line "Enter the word to Replace with : ")
(setq ReplaceWord (read-line))
;(write-line ReplaceWord)
(defvar flag 0)
(loop for i from 0 to (- (length para) (length findWord))
    do(setq flag 0)
    do(if(> (+ i (length findWord)) (length para))
        (return )
    )
    do(loop for j from 0 to (- (length findWord) 1)
        do(if (char/= (char para (+ i j)) (char findWord j))
            (setf flag 1)
        )
    )
    do(if (= flag 0)
        (setf para (concatenate 'string (subseq para 0 i) ReplaceWord (subseq para (+ i (length findWord)))))
    )
)
(terpri)
(write-line "Paragraph after replacing the word : ")
(write-line para)
